import type { CheckDefinition } from './check-definition.types.js';

export const CHECKS: readonly CheckDefinition[] = [
  // ── connectivity ──────────────────────────────────────────────────────────
  {
    id: 'uplink-port-status',
    groupId: 'connectivity',
    label: 'Uplink Port Status',
    description: 'Verifies the uplink port is operationally up',
    needs: ['uplinkPort', 'uplinkPortStatus'],
    gates: [],
    timeoutMs: 10_000,
  },
  {
    id: 'uplink-port-errors',
    groupId: 'connectivity',
    label: 'Uplink Port Errors',
    description: 'Checks for excessive input/output errors on the uplink port',
    needs: ['uplinkPort', 'uplinkPortErrors'],
    gates: ['uplink-port-status'],
    timeoutMs: 10_000,
  },
  {
    id: 'mgmt-ip-assigned',
    groupId: 'connectivity',
    label: 'Management IP Assigned',
    description: 'Verifies a management IP address is assigned (irb or me0)',
    needs: ['managementIp'],
    gates: [],
    timeoutMs: 10_000,
  },
  {
    id: 'mgmt-vlan-reachable',
    groupId: 'connectivity',
    label: 'Management VLAN Reachable',
    description: 'Pings the management gateway to verify layer-2 reachability',
    needs: ['managementIp', 'defaultGateway'],
    gates: ['mgmt-ip-assigned'],
    timeoutMs: 15_000,
  },
  {
    id: 'default-gateway-ping',
    groupId: 'connectivity',
    label: 'Default Gateway Ping',
    description: 'Pings the default gateway to confirm layer-3 forwarding',
    needs: ['defaultGateway'],
    gates: ['mgmt-ip-assigned'],
    timeoutMs: 15_000,
  },
  {
    id: 'mtu-check',
    groupId: 'connectivity',
    label: 'MTU Check',
    description: 'Sends a large ICMP packet to detect MTU black holes on the path to Mist',
    needs: ['defaultGateway', 'mistEndpoint'],
    gates: ['default-gateway-ping'],
    timeoutMs: 20_000,
  },

  // ── routing ───────────────────────────────────────────────────────────────
  {
    id: 'default-route-present',
    groupId: 'routing',
    label: 'Default Route Present',
    description: 'Confirms a 0.0.0.0/0 route exists in the routing table',
    needs: ['defaultGateway'],
    gates: [],
    timeoutMs: 10_000,
  },
  {
    id: 'default-route-via-gateway',
    groupId: 'routing',
    label: 'Default Route via Gateway',
    description: 'Verifies the default route next-hop matches the expected gateway',
    needs: ['defaultGateway'],
    gates: ['default-route-present'],
    timeoutMs: 10_000,
  },
  {
    id: 'routing-table-size',
    groupId: 'routing',
    label: 'Routing Table Size',
    description: 'Warns if the routing table is unexpectedly large or empty',
    needs: [],
    gates: ['default-route-present'],
    timeoutMs: 10_000,
  },
  {
    id: 'arp-gateway',
    groupId: 'routing',
    label: 'ARP — Default Gateway',
    description: 'Checks ARP cache has a valid entry for the default gateway',
    needs: ['defaultGateway'],
    gates: ['default-gateway-ping'],
    timeoutMs: 10_000,
  },
  {
    id: 'arp-mist-ep',
    groupId: 'routing',
    label: 'ARP — Mist Endpoint',
    description: 'Confirms ARP resolution succeeds for the Mist cloud endpoint IP',
    needs: ['mistEndpoint'],
    gates: ['default-gateway-ping'],
    timeoutMs: 15_000,
  },

  // ── dns ───────────────────────────────────────────────────────────────────
  {
    id: 'dns-resolution',
    groupId: 'dns',
    label: 'DNS Resolution',
    description: 'Verifies at least one configured DNS server is reachable',
    needs: ['dnsServers'],
    gates: ['default-gateway-ping'],
    timeoutMs: 15_000,
  },
  {
    id: 'dns-mist-ep',
    groupId: 'dns',
    label: 'DNS — Mist Endpoint',
    description: 'Resolves the Mist cloud WebSocket endpoint hostname',
    needs: ['dnsServers', 'mistEndpoint'],
    gates: ['dns-resolution'],
    timeoutMs: 15_000,
  },
  {
    id: 'dns-ntp',
    groupId: 'dns',
    label: 'DNS — NTP Servers',
    description: 'Resolves configured NTP server hostnames',
    needs: ['dnsServers'],
    gates: ['dns-resolution'],
    timeoutMs: 15_000,
  },

  // ── mist-cloud ────────────────────────────────────────────────────────────
  {
    id: 'jma-state',
    groupId: 'mist-cloud',
    label: 'JMA State',
    description: 'Reads switch self-reported JMA cloud connectivity state code',
    needs: ['jmaState'],
    gates: [],
    timeoutMs: 10_000,
  },
  {
    id: 'mist-ep-reachable',
    groupId: 'mist-cloud',
    label: 'Mist Endpoint Reachable',
    description: 'Pings the Mist cloud WebSocket endpoint IP',
    needs: ['mistEndpoint'],
    gates: ['dns-mist-ep'],
    timeoutMs: 20_000,
  },
  {
    id: 'ntp-sync',
    groupId: 'mist-cloud',
    label: 'NTP Sync',
    description: 'Verifies NTP is synchronised — clock skew causes TLS failures',
    needs: [],
    gates: ['dns-ntp'],
    timeoutMs: 15_000,
  },
  {
    id: 'mist-websocket',
    groupId: 'mist-cloud',
    label: 'Mist WebSocket',
    description: 'Confirms the Mist WebSocket connection is established (JMA state 111)',
    needs: ['jmaState'],
    gates: ['mist-ep-reachable', 'ntp-sync'],
    timeoutMs: 15_000,
  },

  // ── history ───────────────────────────────────────────────────────────────
  {
    id: 'mist-last-seen',
    groupId: 'history',
    label: 'Mist Last Seen',
    description: 'Reports when Mist last saw the device online based on API last_seen field',
    needs: ['mistLastSeen'],
    gates: [],
    timeoutMs: 30_000,
  },
  {
    id: 'mcd-logs-at-offline',
    groupId: 'history',
    label: 'MCD Logs at Offline',
    description: 'Fetches MCD/JMD log entries from the switch around the time it went offline',
    needs: ['mcdLogLines', 'offlineAt'],
    gates: ['mist-last-seen'],
    timeoutMs: 30_000,
  },
  {
    id: 'config-changes-at-offline',
    groupId: 'history',
    label: 'Config Changes at Offline',
    description: 'Checks Mist event log for SW_CONFIG_CHANGED_BY_USER events near the offline window',
    needs: ['mistEventsNearOffline', 'offlineAt'],
    gates: ['mist-last-seen'],
    timeoutMs: 30_000,
  },
] as const;
